name: Fortran CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Fortran
      uses: fortran-lang/setup-fortran@v1.6.1

    # - name: Install dependencies
    #   de

    - name: Build application
      run: |
        gfortran -o myapp src/*.f90

    # - name: Run tests
    #   run: |
    #     ./myapp