name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: setup fortran
      uses: fortran-lang/setup-fortran@main

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build application
      run: |
        gfortran -fprofile-arcs -ftest-coverage -O0 -o SOLA src/*.f90
        # ls -l

    - name: tar files
      run: |
        tar -czvf SOLA.tar.gz SOLA *.gcno
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: APP
        path: SOLA.tar.gz

  tests:
    runs-on: ubuntu-24.04
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: APP

    - name: Extract files
      run: |
        tar -xzvf SOLA.tar.gz

    - name: Run tests
      run: |
        ./SOLA
        ls -l

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: COVERAGE
        path: |
          *.gcno
          *.gcda
  
  coverage:
    runs-on: ubuntu-24.04
    needs: tests
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: COVERAGE
    - name: list files
      run: |
        ls -l
        
    - name: coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        