name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: setup fortran
      uses: fortran-lang/setup-fortran@main

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build application
      run: |
        gfortran -fprofile-arcs -ftest-coverage -O0 -o SOLA src/*.f90
        ls -la

  tests:
    runs-on: ubuntu-24.04
    needs: build
    steps:
    - name: Run tests
      run: |
        ./SOLA
        ls -la

  coverage:
    runs-on: ubuntu-24.04
    needs: tests
    steps:
    - name: coverage
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}