name: Build Fortran docker image

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              
            - uses: azure/docker-login@v1
              with:
                login-server: ghcr.io
                username: "motezuki"
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build docker image
              run: |
                docker build . --file .github/workflows/Dockerfile --tag ghcr.io/motezuki/fortran-dockerimage:latest

            - name: Docker push
              run: |
                docker push ghcr.io/motezuki/fortran-dockerimage:latest
               
